namespace Medbot {
    internal static class Login {
        private readonly static string botName = "medvedibot";
        private readonly static string botFullTwitchName = "MedvediBot";
        private readonly static string password = "oauth:b1a430jprrd6jel5x6irn406hok9pq"; 
        private readonly static string channel = "medvedibot";

        /// <summary>
        /// Name of the bot (username of bot's Twitch account) in lower case !
        /// </summary>
        internal static string BotName { get { return botName.ToLower(); } }

        /// <summary>
        /// Password to bot's account
        /// Password must contain oauth: prefix - generated by twitchapps.com/tmi
        /// </summary>
        internal static string BotPassword { get { return password; } }

        /// <summary>
        /// Name of channel where bot should join in lower case
        /// </summary>
        internal static string Channel { get { return channel.ToLower(); } }

        /// <summary>
        /// Gets full name of bot's twitch account, including upper and lower case
        /// </summary>
        internal static string BotFullTwitchName { get { return botFullTwitchName; } }
    }
}
