using System;

namespace Medbot
{
    internal static class Login
    {
        private static string botName = String.Empty;
        private static string oauth = String.Empty;
        private static string channel = String.Empty;

        /// <summary>
        /// Name of the bot (username of bot's Twitch account) in lower case !
        /// </summary>
        internal static string BotName
        {
            get { return botName.ToLower(); }
            set { botName = value; }
        }

        /// <summary>
        /// Password to bot's account
        /// Password contains oauth: prefix - generated by twitchapps.com/tmi
        /// </summary>
        internal static string BotOauthWithPrefix { get; private set; } = "oauth:" + oauth;

        /// <summary>
        /// Gets bot's oauth string without oauth prefix
        /// </summary>
        internal static string BotOauth
        {
            get { return oauth; }
            set
            {
                oauth = value;
                BotOauthWithPrefix = "oauth:" + value;
            }
        }

        /// <summary>
        /// Gets bot's Client ID
        /// </summary>
        internal static string ClientID { get; set; } = String.Empty;

        /// <summary>
        /// Name of channel where bot should join in lower case
        /// </summary>
        internal static string Channel { get { return channel.ToLower(); } set { channel = value; } }

        /// <summary>
        /// Gets full name of bot's twitch account, including upper and lower case
        /// </summary>
        internal static string BotFullTwitchName { get; set; } = String.Empty;

        /// <summary>
        /// Gets bool if login credentials are valid
        /// </summary>
        internal static bool IsLoginCredentialsValid =>
                        !String.IsNullOrEmpty(BotName) &&
                        !String.IsNullOrEmpty(BotOauthWithPrefix) &&
                        !String.IsNullOrEmpty(Channel);
    }
}